canonifyURLs = false
relativeURLs = false



[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]
  footer = []

[outputFormats.footerSection]
# empty on purpose

disableKinds = ["footerSection", "RSS"]

[module]
  [[module.imports]]
    path = "github.com/zetxek/adritian-free-hugo-theme"

  ## Base mounts
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "i18n"
    target = "i18n"

  [[module.mounts]]
    source = "layouts"
    target = "layouts"

  [[module.mounts]]
    source = "static"
    target = "static"

  # Theme-required mounts (Bootstrap, etc.)
  [[module.mounts]]
    source = "node_modules/bootstrap/scss"
    target = "assets/scss/bootstrap"

  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js"
    target = "assets/js/bootstrap"

  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/vendor/bootstrap.bundle.min.js"

  [[module.mounts]]
    source = "node_modules/bootstrap-print-css/css/bootstrap-print.css"
    target = "assets/css/bootstrap-print.css"

[params]
  title = "STASER Lab"
  description = "Socio Technical Aspects of Software EngineERing"
  sections = ["about","research","people","publications","news","contact"]
  logo = "/img/logo.png"
  homepageExperienceCount = 6

  [params.analytics]
    vercelPageInsights = false
    vercelAnalytics = false

    [params.analytics.googleAnalytics]
      code = "UA-XXXXX-Y"
      enabled = false
    [params.analytics.googleTagManager]
      code = "GTM-XXXXX"
      enabled = false

[build]
  writeStats = true

  [build.buildStats]
    enabledFor = ["scss"]
    disableClasses = false
    disableIDs = false
    disableTags = false
    enable = true

[params.languages.selector.disable]
  footer = false
  header = false
  mobileHeader = false

[languages]

  [languages.en]
    disabled = false
    languageCode = "en"
    languageDirection = "ltr"
    languageName = "English"
    title = ""
    weight = 0

  [languages.en.menus]
    # HEADER (single-page anchors; add leading "/" and fix research)
    [[languages.en.menus.header]]
      name = "About"
      URL = "/#about"
      weight = 1

    [[languages.en.menus.header]]
      name = "Research"
      URL = "/#research"  
      weight = 2

    [[languages.en.menus.header]]
      name = "People"
      URL = "/#people"
      weight = 3

    [[languages.en.menus.header]]
      name = "Publications"
      URL = "/#publications"
      weight = 4
    
    [[languages.en.menus.header]]
      name = "news"
      URL = "/#news"
      weight = 5


    [[languages.en.menus.header]]
      pre = "email"
      name = "email"
      URL = "/#contact"
      weight = 6




[languages.es]
disabled = false
languageCode = "es"
languageDirection = "ltr"
languageName = "Español"
title = ""
weight = 0

[languages.es.menus]
  [[languages.es.menus.header]]
    name = "Sobre mí"
    URL  = "/es/#sobre-mi"
    weight = 1
  [[languages.es.menus.header]]
    name = "Investigación"
    URL  = "/es/#investigacion"
    weight = 2
  [[languages.es.menus.header]]
    name = "Equipo"
    URL  = "/es/#equipo"
    weight = 3
  [[languages.es.menus.header]]
    name = "Publicaciones"
    URL  = "/es/#publications"
    weight = 4
  [[languages.es.menus.header]]
    name = "Noticias"
    URL  = "/es/#noticias"
    weight = 5
  [[languages.es.menus.header]]
    pre  = "email"
    name = "Contacto"
    URL  = "/es/#contacto"
    weight = 6

    #FRENCH
    [languages.fr]
    disabled = false
    languageCode = "fr"
    languageDirection = "ltr"
    languageName = "Français"
    title = ""
    weight = 0

    [languages.fr.menus]
    [[languages.fr.menus.header]]
        name = "À propos"
        URL  = "/fr/#a-propos"
        weight = 1
    [[languages.fr.menus.header]]
        name = "Recherche"
        URL  = "/fr/#recherche"
        weight = 2
    [[languages.fr.menus.header]]
        name = "Équipe"
        URL  = "/fr/#equipe"
        weight = 3
    [[languages.fr.menus.header]]
        name = "Publications"
        URL  = "/fr/#publications"
        weight = 4
    [[languages.fr.menus.header]]
        name = "Actualités"
        URL  = "/fr/#actualites"
        weight = 5
    [[languages.fr.menus.header]]
        pre  = "email"
        name = "Contact"
        URL  = "/fr/#contact"
        weight = 6


    #Plugins
    [params.plugins]
    # CSS
    [[params.plugins.css]]
    URL = "css/adritian-icons.css"

    [[params.plugins.css]]
    URL = "css/bootstrap-print.css"

    [[params.plugins.css]]
    URL = "css/custom.css"




    # JS
    [[params.plugins.js]]
        URL = "js/rad-animations.js"
    [[params.plugins.js]]
        URL = "js/sticky-header.js"
    [[params.plugins.js]]
        URL = "js/library/fontfaceobserver.js"


  # SCSS
  [[params.plugins.scss]]
    URL = "scss/adritian.scss"

[params.colorTheme]
  [params.colorTheme.selector.disable]
    footer = false
    header = false
    mobileHeader = false

[params.pageTransition]
  enabled = true

[params.blog]
  layout = "sidebar-right"
  sidebarWidth = "25"
  showCategories = true
  showRecentPosts = true
  recentPostCount = 5
  listStyle = "summary"
  featured_sort_by_weight = true
  featured_sort_by_date = false

[params.experience]
  showJobCard = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    lineNos = false
    style = "github"

[imaging]
  resampleFilter = "Lanczos"
  quality = 85
  anchor = "Smart"

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepDefaultAttrVals = true
      keepWhitespace = false
    [minify.tdewolff.css]
      precision = 0
    [minify.tdewolff.js]
      precision = 0
